<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $towns = [
            ['Arlington', 1],
            ['Bethlehem', 1],
            ['Clarens', 1],
            ['Clocolan', 1],
            ['Cornelia', 1],
            ['Excelsior', 1],
            ['Ficksburg', 1],
            ['Fouriesburg', 1],
            ['Harrismith', 1],
            ['Hobhouse', 1],
            ['Kestell', 1],
            ['Ladybrand', 1],
            ['Lindley', 1],
            ['Marquard', 1],
            ['Memel', 1],
            ['Paul Roux', 1],
            ['Petrus Steyn', 1],
            ['Phuthaditjhaba', 1],
            ['Reitz', 1],
            ['Rosendal', 1],
            ['Senekal', 1],
            ['Steynsrus', 1],
            ['Swinburne', 1],
            ['Tweespruit', 1],
            ['Van Reenen', 1],
            ['Vrede', 1],
            ['Winburg', 1],
            ['Allanridge', 1],
            ['Warden', 1],
            ['Boshof', 1],
            ['Bothaville', 1],
            ['Brandfort', 1],
            ['Bultfontein', 1],
            ['Dealesville', 1],
            ['Hennenman', 1],
            ['Hertzogville', 1],
            ['Hoopstad', 1],
            ['Mvela', 1],
            ['Odendaalsrus', 1],
            ['Theunissen', 1],
            ['Ventersburg', 1],
            ['Verkeerdevlei', 1],
            ['Virginia', 1],
            ['Welkom', 1],
            ['Wesselsbron', 1],
            ['Winburg', 1],
            ['Deneysville', 1],
            ['Edenville', 1],
            ['Frankfort', 1],
            ['Heilbron', 1],
            ['Koppies', 1],
            ['Kroonstad', 1],
            ['Oranjeville', 1],
            ['Parys', 1],
            ['Sasolburg', 1],
            ['Tweeling', 1],
            ['Viljoenskroon', 1],
            ['Villiers', 1],
            ['Vredefort', 1],
            ['Bethulie', 1],
            ['Bloemfontein', 1],
            ['Botshabelo', 1],
            ['Edenburg', 1],
            ['Bothaville', 1],
            ['Dewetsdorp', 1],
            ['Bultfontein', 1],
            ['Fauresmith', 1],
            ['Jacobsdal', 1],
            ['Jagersfontein', 1],
            ['Koffiefontein', 1],
            ['Luckhoff', 1],
            ['Petrusburg', 1],
            ['Philippolis', 1],
            ['Reddersburg', 1],
            ['Rouxville', 1],
            ['Smithfield', 1],
            ['Springfontein', 1],
            ['Wesselsbron', 1],
            ['Thaba Nchu', 1],
            ['Trompsburg', 1],
            ['Van Stadensrus', 1],
            ['Wepener', 1],
            ['Zastron', 1],

            ['Alexandra', 2],
            ['Diepsloot', 2],
            ['Ennerdale', 2],
            ['Johannesburg', 2],
            ['Lenasia', 2],
            ['Modderfontein', 2],
            ['Midrand', 2],
            ['Orange Farm', 2],
            ['Randburg', 2],
            ['Roodepoort', 2],
            ['Sandton', 2],
            ['Soweto', 2],
            ['Naturena', 2],
            ['Alberton', 2],
            ['Bedfordview', 2],
            ['Benoni', 2],
            ['Boksburg', 2],
            ['Brakpan', 2],
            ['Bapsfontein', 2],
            ['Clayville', 2],
            ['Daveyton', 2],
            ['Duduza', 2],
            ['Edenvale', 2],
            ['Etwatwa', 2],
            ['Germiston', 2],
            ['Isando', 2],
            ['Kempton Park', 2],
            ['Katlehong', 2],
            ['KwaThema', 2],
            ['Dunnottar', 2],
            ['Nigel', 2],
            ['Reiger Park', 2],
            ['Springs', 2],
            ['Thembisa', 2],
            ['Thokoza', 2],
            ['Tsakane', 2],
            ['Vosloorus', 2],
            ['Wattville', 2],
            ['Atteridgeville', 2],
            ['Bronberg', 2],
            ['Bronkhorstspruit', 2],
            ['Centurion', 2],
            ['Cullinan', 2],
            ['Ekangala', 2],
            ['Hammanskraal', 2],
            ['Ga-Rankuwa', 2],
            ['Irene', 2],
            ['Mabopane', 2],
            ['Mamelodi', 2],
            ['Pretoria', 2],
            ['Rayton', 2],
            ['Refilwe', 2],
            ['Soshanguve', 2],
            ['Winterveld', 2],
            ['Zithobeni', 2],
            ['Boipatong', 2],
            ['Bophelong', 2],
            ['Evaton', 2],
            ['Sebokeng', 2],
            ['Sharpeville', 2],
            ['Vanderbijlpark', 2],
            ['Vereeniging', 2],
            ['Meyerton', 2],
            ['Randvaal', 2],
            ['Walkerville', 2],
            ['Devon', 2],
            ['Heidelberg', 2],
            ['Impumelelo', 2],
            ['Ratanda', 2],
            ['Carletonville', 2],
            ['Khutsong', 2],
            ['Fochville', 2],
            ['Kokosi', 2],
            ['Greenspark', 2],
            ['Wedela', 2],
            ['Welverdiend', 2],
            ['Blybank', 2],
            ['Hekpoort', 2],
            ['Kagiso', 2],
            ['Kromdraai', 2],
            ['Krugersdorp', 2],
            ['Magaliesburg', 2],
            ['Muldersdrift', 2],
            ['Munsieville', 2],
            ['Rietvallei', 2],
            ['Silverfields', 2],
            ['Tarlton', 2],
            ['Bhongweni', 2],
            ['Brandvlei', 2],
            ['Mohlakeng', 2],
            ['Panvlak Gold Mine', 2],
            ['Randfontein', 2],
            ['Toekomsrus', 2],
            ['Zenzele', 2],
            ['Bekkersdal', 2],
            ['Westonaria', 2],
            ['Dannhauser', 3],
            ['Hattingspruit', 3],
            ['Newcastle', 3],
            ['Madadeni', 3],
            ['Osizweni', 3],
            ['Charlestown', 3],
            ['Ngagane', 3],
            ['Emadlangeni', 3],
            ['Kingsley', 3],
            ['ekuPhakameni', 3],
            ['Adams Mission', 3],
            ['Amanzimtoti', 3],
            ['Bothas Hill', 3],
            ['Cato Ridge', 3],
            ['Chatsworth', 3],
            ['Clermont', 3],
            ['Durban', 3],
            ['Gillitts', 3],
            ['Hillcrest', 3],
            ['Inchanga', 3],
            ['Inanda', 3],
            ['Isipingo', 3],
            ['Kingsburgh', 3],
            ['Kloof', 3],
            ['KwaMashu', 3],
            ['La Mercy', 3],
            ['Hammarsdale', 3],
            ['New Germany', 3],
            ['Ntuzuma', 3],
            ['Dannhauser', 3],
            ['oThongathi', 3],
            ['DanPinetownnhauser', 3],
            ['Phoenix', 3],
            ['Queensburgh', 3],
            ['Prospecton', 3],
            ['Umbumbulu', 3],
            ['Shallcross', 3],
            ['eMdloti', 3],
            ['Umgababa', 3],
            ['uMhlanga', 3],
            ['eMkhomazi', 3],
            ['Umlazi', 3],
            ['Westville', 3],
            ['Verulam', 3],
            ['Bulwer', 3],
            ['Franklin', 3],
            ['Himeville', 3],
            ['Ixopo', 3],
            ['Kokstad', 3],
            ['Underberg', 3],
            ['Umzimkulu', 3],
            ['Ballito', 3],
            ['KwaDukuza', 3],
            ['Salt Rock', 3],
            ['Maphumulo', 3],
            ['Mandeni', 3],
            ['Anerley', 3],
            ['Bazley Beach', 3],
            ['Dududu', 3],
            ['Hibberdene', 3],
            ['Harding', 3],
            ['eZinqoleni', 3],
            ['Ifafa Beach', 3], ['Kelso', 3],
            ['Margate', 3],
            ['Melville', 3], ['Mthwalume', 3],
            ['Munster', 3],
            ['Pennington', 3], ['  Park Rynie', 3],
            ['Port Edward', 3],
            ['Port Shepstone', 3],
            ['Ramsgate', 3],
            ['Scottburgh', 3],
            ['Sezela', 3],
            [' Shelly Beach', 3],
            ['Southbroom', 3],
            ['Umtentweni', 3],
            ['Umzinto', 3],
            ['Umzumbe', 3],
            ['Weza', 3],
            ['Uvongo', 3],

            ['Balgowan', 3],
            ['Boston', 3],
            ['Hilton', 3],
            ['Howick', 3],
            ['Merrivale', 3],
            ['Mooi River', 3],
            ['New Hanover', 3],
            ['Pietermaritzburg', 3],
            ['Richmond', 3],
            ['Wartburg', 3],
            ['Dalton', 3],
            ['Harding', 3],
            ['Hluhluwe', 3],
            ['Ingwavuma', 3],
            ['Mkuze', 3],
            ['Mtubatuba', 3],
            ['Ubombo', 3],
            ['Jozini', 3],
            ['Mbazwana', 3],
            ['Manguzi', 3],
            ['Dundee', 3],
            ['Glencoe', 3],
            ['Greytown', 3],
            ['Kranskop', 3],
            ['Wasbank', 3],
            ['Pomeroy', 3],
            ['Nquthu', 3],
            ['Bergville', 3],
            ['Elandslaagte', 3],
            ['Estcourt', 3],
            ['Colenso', 3],
            ['Ladysmith', 3],
            ['Empangeni', 3],
            ['Eshowe', 3],
            ['Melmoth', 3],
            ['Mtunzini', 3],
            ['Richards Bay', 3],
            ['Nkandla', 3],
            ['Babanango', 3],
            ['Louwsburg', 3],
            ['Mahlabatini', 3],
            ['Nongoma', 3],
            ['Paulpietersburg', 3],
            ['Ulundi', 3],
            ['Pongola', 3],
            ['Vryheid', 3],
            ['Uvongo', 3],
            ['Uvongo', 3],
            ['Uvongo', 3],
            ['Uvongo', 3],

            ['Afguns', 4],
            ['Alldays', 4],
            ['Bandelierkop', 4],
            ['Ba-Phalaborwa', 4],
            ['Bela-Bela', 4],
            ['Bochum', 4],
            ['Bosbokrand', 4],
            ['Dendron', 4],
            ['Duiwelskloof', 4],
            ['Elim', 4],
            ['Ellisras', 4],
            ['Gravelotte', 4],
            ['Haenertsburg', 4],
            ['Hoedspruit', 4],
            ['Klaserie', 4],
            ['Lebowakgomo', 4],
            ['Lephalale', 4],
            ['Letsitele', 4],
            ['Leydsdorp', 4],
            ['Louis Trichardt', 4],
            ['Modimolle', 4],
            ['Modjadjiskloof', 4],
            ['Mogwadi', 4],
            ['Mokopane', 4],
            ['Mookgophong', 4],
            ['Messina', 4],
            ['Musina', 4],
            ['Naboomspruit', 4],
            ['Nylstroom', 4],
            ['Ofcolaco', 4],
            ['Phalaborwa', 4],
            ['Polokwane', 4],
            ['Mokopane', 4],
            ['Roedtan', 4],
            ['Senwabarwana', 4],
            ['Seshego', 4],
            ['Sekgopo', 4],
            ['Thabazimbi', 4],
            ['Thohoyandou', 4],
            ['Tzaneen', 4],
            ['Vaalwater', 4],
            ['Vivo', 4],
            ['Zebedeila', 4],
            ['Zion City Moria', 4],

            ['Aankoms', 5],
            ['Acornhoek', 5],
            ['Amersfoort', 5],
            ['Amsterdam', 5],
            ['Anysspruit', 5],
            ['Argent', 5],
            ['Avoca', 5],
            ['Avontuur', 5],
            ['Badplaas', 5],
            ['Balfour', 5],
            ['Balmoral', 5],
            ['Bankkop', 5],
            ['Barberton', 5],
            ['Belfast', 5],
            ['Berbice', 5],
            ['Bethal', 5],
            ['Bettiesdam', 5],
            ['Branddraai', 5],
            ['Braunschweig', 5],
            ['Breyten', 5],
            ['Brondal', 5],
            ['Bushbuckridge', 5],
            ['Carolina', 5],
            ['Chrissiesmeer', 5],
            ['Davale', 5],
            ['Delmas', 5],
            ['Diepdale', 5],
            ['Diepgezet', 5],
            ['Dullstroom', 5],
            ['Dundonald', 5],
            ['Eerstehoek', 5],
            ['Ekulindeni', 5],
            ['Elukwatini', 5],
            ['Embhuleni', 5],
            ['Emphuluzi', 5],
            ['Enkhaba', 5],
            ['Ermelo', 5],
            ['Fernie', 5],
            ['Glenmore', 5],
            ['Graskop', 5],
            ['Greylingstad', 5],
            ['Hartebeeskop', 5],
            ['Hazyview', 5],
            ['Hectorspruit', 5],
            ['Kaapmuiden', 5],
            ['Kinross', 5],
            ['Komatipoort', 5],
            ['KwaMhlanga', 5],
            ['Lochiel', 5],
            ['Loopspruit', 5],
            ['Lydenburg', 5],
            ['Machadodorp', 5],
            ['Malelane', 5],
            ['Mbhejeka', 5],
            ['Middelburg', 5],
            ['Moddergat', 5],
            ['Nelspruit', 5],
            ['Ngodwana', 5],
            ['Ohrigstad', 5],
            ['Perdekop', 5],
            ['Piet Retief', 5],
            ['Pilgrims Rest', 5],
            ['Sabie', 5],
            ['Secunda', 5],
            ['Siyabuswa', 5],
            ['Skukuza', 5],
            ['Standerton', 5],
            ['Trichardt', 5],
            ['Vaalbank', 5],
            ['Volksrust', 5],
            ['Wakkerstroom', 5],
            ['Waterval Boven', 5],
            ['Waterval Onder', 5],
            ['White River', 5],
            ['Witbank', 5],

            ['Barkly West', 6],
            ['Campbell', 6],
            ['Delportshoop', 6],
            ['Douglas', 6],
            ['Griquatown', 6],
            ['Hartswater', 6],
            ['Jan Kempdorp', 6],
            ['Kimberley', 6],
            ['Modder River', 6],
            ['Ulco', 6],
            ['Warrenton', 6],
            ['Windsorton', 6],

            ['Andriesvale', 6],
            ['Askham', 6],
            ['Augrabies', 6],
            ['Danielskuil', 6],
            ['Groblershoop', 6],
            ['Kakamas', 6],
            ['Kanoneiland', 6],
            ['Keimoes', 6],
            ['Kenhardt', 6],
            ['Lime Acres', 6],
            ['Louisvale', 6],
            ['Mier', 6],
            ['Olifantshoek', 6],
            ['Onseepkans', 6],
            ['Postmasburg', 6],
            ['Putsonderwater', 6],
            ['Riemvasmaak', 6],
            ['Rietfontein', 6],
            ['Upington', 6],
            ['Kathu', 6],
            ['Kuruman', 6],

            ['Aggeneys', 6],
            ['Alexander Bay', 6],
            ['Carolusberg', 6],
            ['Concordia', 6],
            ['Garies', 6],
            ['Hondeklip', 6],
            ['Kamieskroon', 6],
            ['Kleinzee', 6],
            ['Nababeep', 6],
            ['Okiep', 6],
            ['Pella', 6],
            ['Pofadder', 6],
            ['Port Nolloth', 6],
            ['Soebatsfontein', 6],
            ['Springbok', 6],
            ['Steinkopf', 6],

            ['Britstown', 6],
            ['Colesberg', 6],
            ['Copperton', 6],
            ['De Aar', 6],
            ['Hanover', 6],
            ['Hopetown', 6],
            ['Hutchinson', 6],
            ['Loxton', 6],
            ['Marydale', 6],
            ['Norvalspont', 6],
            ['Noupoort', 6],
            ['Orania', 6],
            ['Petrusville', 6],
            ['Philipstown', 6],
            ['Prieska', 6],
            ['Richmond', 6],
            ['Strydenburg', 6],
            ['Vanderkloof', 6],
            ['Victoria West', 6],
            ['Vosburg', 6],

            ['Amalia', 7],
            ['Bray', 7],
            ['Ganyesa', 7],
            ['Mareetsane', 7],
            ['Morokweng', 7],
            ['Motlhabeng', 7],
            ['Reivilo', 7],
            ['Schweizer-Reneke', 7],
            ['Setlagole', 7],
            ['Stella', 7],
            ['Taung', 7],
            ['Tosca', 7],
            ['Vryburg', 7],
            ['Setlopo', 7],

            ['Babelegi', 7],
            ['Beestekraal', 7],
            ['Brits', 7],
            ['Broederstroom', 7],
            ['Derby', 7],
            ['Hartbeespoort', 7],
            ['Hekpoort', 7],
            ['Jericho', 7],
            ['Kosmos', 7],
            ['Koster', 7],
            ['Kroondal', 7],
            ['Legogolwe', 7],
            ['Maanhaarrand', 7],
            ['Manamakgoteng', 7],
            ['Mmakau', 7],
            ['Mogwase', 7],
            ['Mooinooi', 7],
            ['Mathibestad', 7],
            ['Mononono', 7],
            ['Ramokokastad', 7],
            ['Rooikoppies', 7],
            ['Rustenburg', 7],
            ['Skeerpoort', 7],
            ['Swartruggens', 7],
            ['Tsitsing', 7],

            ['Biesiesvlei', 7],
            ['Coligny', 7],
            ['Delareyville', 7],
            ['Ganyesa', 7],
            ['Groot Marico', 7],
            ['Itsoseng', 7],
            ['Lichtenburg', 7],
            ['Mareetsane', 7],
            ['Mafeking', 7],
            ['Mmabatho', 7],
            ['Ottosdal', 7],
            ['Ottoshoop', 7],
            ['Sannieshof', 7],
            ['Welbedacht', 7],
            ['Zeerust', 7],

            ['Bloemhof', 7],
            ['Christiana', 7],
            ['Hartbeesfontein', 7],
            ['Klerksdorp', 7],
            ['Leeudoringstad', 7],
            ['Makwassie', 7],
            ['Orkney', 7],
            ['Potchefstroom', 7],
            ['Stilfontein', 7],
            ['Ventersdorp', 7],
            ['Wolmaransstad', 7],

            //Cape Metropole
            ['Atlantis', 8],
            ['Bellville', 8],
            ['Blue Downs', 8],
            ['Brackenfell', 8],
            ['Cape Town', 8],
            ['Crossroads', 8],
            ['Durbanville', 8],
            ['Eerste River', 8],
            ['Elsies River', 8],
            ['Fish Hoek', 8],
            ['Goodwood', 8],
            ['Gordons Bay', 8],
            ['Guguletu', 8],
            ['Hout Bay', 8],
            ['Khayelitsha', 8],
            ['Kraaifontein', 8],
            ['Kuils River', 8],
            ['Langa', 8],
            ['Macassar', 8],
            ['Melkbosstrand', 8],
            ['Mfuleni', 8],
            ['Milnerton', 8],
            ['Mitchells Plain', 8],
            ['Noordhoek', 8],
            ['Nyanga', 8],
            ['Observatory', 8],
            ['Parow', 8],
            ['Simons Town', 8],
            ['Somerset West', 8],
            ['Strand', 8],

            //West Coast
            ['Aurora', 8],
            ['Bitterfontein', 8],
            ['Chatsworth', 8],
            ['Citrusdal', 8],
            ['Clanwilliam', 8],
            ['Darling', 8],
            ['Doringbaai', 8],
            ['Dwarskersbos', 8],
            ['Ebenhaeser', 8],
            ['Eendekuil', 8],
            ['Elands Bay', 8],
            ['Goedverwacht', 8],
            ['Graafwater', 8],
            ['Grotto Bay', 8],
            ['Hopefield', 8],
            ['Jacobsbaai', 8],
            ['Jakkalsfontein', 8],
            ['Kalbaskraal', 8],
            ['Klawer', 8],
            ['Koekenaap', 8],
            ['Koringberg', 8],
            ['Lamberts Bay', 8],
            ['Langebaan', 8],
            ['Langebaanweg', 8],
            ['Lutzville', 8],
            ['Malmesbury', 8],
            ['Moorreesburg', 8],
            ['Paternoster', 8],
            ['Piketberg', 8],
            ['Porterville', 8],
            ['Redelinghuys', 8],
            ['Riebeek-Kasteel', 8],
            ['Riebeek West', 8],
            ['Saldanha', 8],
            ['St Helena Bay', 8],
            ['Strandfontein', 8],
            ['Vanrhynsdorp', 8],
            ['Velddrif', 8],
            ['Vredenburg', 8],
            ['Vredendal', 8],
            ['Wupperthal', 8],
            ['Yzerfontein', 8],

//Cape Winelands
            ['Ashton', 8],
            ['Bonnievale', 8],
            ['Ceres', 8],
            ['De Doorns', 8],
            ['Denneburg', 8],
            ['Franschhoek', 8],
            ['Gouda', 8],
            ['Kayamandi', 8],
            ['Klapmuts', 8],
            ['Kylemore', 8],
            ['Languedoc', 8],
            ['McGregor', 8],
            ['Montagu', 8],
            ['Op-die-Berg', 8],
            ['Paarl', 8],
            ['Pniel', 8],
            ['Prince Alfred Hamlet', 8],
            ['Rawsonville', 8],
            ['Robertson', 8],
            ['Robertsvlei', 8],
            ['Rozendal', 8],
            ['Saron', 8],
            ['Stellenbosch', 8],
            ['Touws River', 8],
            ['Tulbagh', 8],
            ['Wellington', 8],
            ['Wemmershoek', 8],
            ['Wolseley', 8],
            ['Worcester', 8],

//Overberg
            ['Arniston', 8],
            ['Baardskeerdersbos', 8],
            ['Bettys Bay', 8],
            ['Birkenhead', 8],
            ['Botrivier', 8],
            ['Bredasdorp', 8],
            ['Caledon', 8],
            ['Dennehof', 8],
            ['De Kelders', 8],
            ['Elgin', 8],
            ['Elim', 8],
            ['Fisherhaven', 8],
            ['Franskraalstrand', 8],
            ['Gansbaai', 8],
            ['Genadendal', 8],
            ['Grabouw', 8],
            ['Greyton', 8],
            ['Hawston', 8],
            ['Hermanus', 8],
            ['Hotagterklip', 8],
            ['Infanta', 8],
            ['Kleinbaai', 8],
            ['Kleinmond', 8],
            ['L Agulhas', 8],
            ['Napier', 8],
            ['Onrusrivier', 8],
            ['Pearly Beach', 8],
            ['Pringle Bay', 8],
            ['Riviersonderend', 8],
            ['Rooi Els', 8],
            ['Stanford', 8],
            ['Struisbaai', 8],
            ['Suiderstrand', 8],
            ['Suurbraak', 8],
            ['Swellendam', 8],
            ['Van Dyksbaai', 8],
            ['Vermont', 8],
            ['Villiersdorp', 8],

//Garden Route
            ['Albertinia', 8],
            ['Boggomsbaai', 8],
            ['Brenton-on-Sea', 8],
            ['Buffelsbaai', 8],
            ['Dana Baai', 8],
            ['De Rust', 8],
            ['Dysselsdorp', 8],
            ['Friemersheim', 8],
            ['George', 8],
            ['Glentana', 8],
            ['Gouritsmond', 8],
            ['Great Brak River', 8],
            ['Groot-Jongensfontein', 8],
            ['Haarlem', 8],
            ['Hartenbos', 8],
            ['Heidelberg', 8],
            ['Herbertsdale', 8],
            ['Herolds Bay', 8],
            ['Keurboomsrivier', 8],
            ['Keurboomstrand', 8],
            ['Knysna', 8],
            ['Kranshoek', 8],
            ['Kurland Estate', 8],
            ['Little Brak River', 8],
            ['Mossel Bay', 8],
            ['Natures Valley', 8],
            ['Noetzie', 8],
            ['Pacaltsdorp', 8],
            ['Plettenberg Bay', 8],
            ['Port Beaufort', 8],
            ['Rheenendal', 8],
            ['Riversdale', 8],
            ['Sedgefield', 8],
            ['Slangrivier', 8],
            ['Stilbaai', 8],
            ['Uniondale', 8],
            ['Volmoed', 8],
            ['Victoria Bay', 8],
            ['Wilderness', 8],
            ['Wittedrift', 8],
            ['Zoar', 8],

//Klein Karoo
            ['Montagu', 8],
            ['Barrydale', 8],
            ['Ladismith', 8],
            ['Calitzdorp', 8],
            ['Oudtshoorn', 8],
            ['De Rust', 8],

            ['Adelaide', 9],
            ['Alice', 9],
            ['Aliwal North', 9],
            ['Sophangisas land', 9],
            ['Barkly East', 9],
            ['Bethulie', 9],
            ['Berlin', 9],
            ['Bisho', 9],
            ['Braunschweig', 9],
            ['Burgersdorp', 9],
            ['Cala', 9],
            ['Cathcart', 9],
            ['Cedarville', 9],
            ['Cofimvaba', 9],
            ['Dohne', 9],
            ['Dordrecht', 9],
            ['East London', 9],
            ['Elliot', 9],
            ['Engcobo', 9],
            ['Fort Beaufort', 9],
            ['Gonubie', 9],
            ['Haga-Haga', 9],
            ['Hamburg', 9],
            ['Hogsback', 9],
            ['Hofmeyr', 9],
            ['Indwe', 9],
            ['Jamestown', 9],
            ['Katberg', 9],
            ['Kei Mouth', 9],
            ['Keiskammahoek', 9],
            ['Kidds Beach', 9],
            ['King Williams Town', 9],
            ['Komga', 9],
            ['Lady Frere', 9],
            ['Lady Grey', 9],
            ['Maclear', 9],
            ['Mdantsane', 9],
            ['Hertzog', 9],
            ['Molteno', 9],
            ['Morgans Bay', 9],
            ['Mount Frere', 9],
            ['Oyster Bay', 9],
            ['Peddie', 9],
            ['Queenstown', 9],
            ['Seymour', 9],
            ['Sterkspruit', 9],
            ['Sterkstroom', 9],
            ['Stutterheim', 9],
            ['Tarkastad', 9],
            ['Tsomo', 9],
            ['Venterstad', 9],
            ['Whittlesea', 9],
            ['Zwelitsha', 9],
//The Western Region
            ['Aberdeen', 9],
            ['Addo', 9],
            ['Alexandria', 9],
            ['Bathurst', 9],
            ['Bedford', 9],
            ['Cookhouse', 9],
            ['Cradock', 9],
            ['Despatch', 9],
            ['Enon', 9],
            ['Port Elizabeth', 9],
            ['Graaff Reinet', 9],
            ['Grahamstown', 9],
            ['Hankey', 9],
            ['Humansdorp', 9],
            ['Jeffreys Bay', 9],
            ['Joubertina', 9],
            ['Kareedouw', 9],
            ['Kenton-on-Sea', 9],
            ['Kirkwood', 9],
            ['Krakeelrivier', 9],
            ['Middelburg', 9],
            ['Nieu-Bethesda', 9],
            ['Patensie', 9],
            ['Paterson', 9],
            ['Port Alfred', 9],
            ['Salem', 9],
            ['Somerset East', 9],
            ['St Francis Bay', 9],
            ['Steynsburg', 9],
            ['Willowmore', 9],
            ['Steytlerville', 9],
            ['Uitenhage', 9],
//The Wild Coast
            ['Bizana', 9],
            ['Butterworth', 9],
            ['Kentani', 9],
            ['Cintsa', 9],
            ['Coffee Bay', 9],
            ['Elliotdale', 9],
            ['Flagstaff', 9],
            ['Idutywa', 9],
            ['Lady Frere', 9],
            ['Libode', 9],
            ['Lusikisiki', 9],
            ['Matatiele', 9],
            ['Mount Fletcher', 9],
            ['Mount Ayliff', 9],
            ['Mount Frere', 9],
            ['Nqamakwe', 9],
            ['Ngqeleni', 9],
            ['Port St Johns', 9],
            ['Qolora Mouth', 9],
            ['Qumbu', 9],
            ['Tabankulu', 9],
            ['Tsolo', 9],
            ['Umtata', 9],
            ['Willowvale', 9],

        ];

        foreach ($towns as $town) {
            DB::table('towns')->insert([
                'town' => $town[0],
                'provinceId' => $town[1],
                'created_at' => now(),
                'updated_at' => now(),
            ]);

        }
    }
}
