INSERT INTO `municipal_districts` (`id`, `municipal_district`, `provinceId`, `created_at`, `updated_at`) VALUES
(NULL, 'Mangaung Metropolitan', 1, NOW(), NOW()),
(NULL, 'Fezile Dabi District', 1, NOW(), NOW()),
(NULL, 'Lejweleputswa District', 1, NOW(), NOW()),
(NULL, 'Thabo Mofutsanyana District', 1, NOW(), NOW()),
(NULL, 'Xhariep District', 1, NOW(), NOW()),
(NULL, 'City of Ekurhuleni Metropolitan', 2, NOW(), NOW()),
(NULL, 'City of Johannesburg Metropolitan', 2, NOW(), NOW()),
(NULL, 'City of Tshwane Metropolitan', 2, NOW(), NOW()),
(NULL, 'Sedibeng District', 2, NOW(), NOW()),
(NULL, 'West Rand District', 2, NOW(), NOW()),
(NULL, 'eThekwini Metropolitan', 3, NOW(), NOW()),
(NULL, 'Amajuba District', 3, NOW(), NOW()),
(NULL, 'Harry Gwala District', 3, NOW(), NOW()),
(NULL, 'iLembe District', 3, NOW(), NOW()),
(NULL, 'King Cetshwayo District', 3, NOW(), NOW()),
(NULL, 'Ugu District', 3, NOW(), NOW()),
(NULL, 'uMgungundlovu District', 3, NOW(), NOW()),
(NULL, 'uMkhanyakude District', 3, NOW(), NOW()),
(NULL, 'uMzinyathi District', 3, NOW(), NOW()),
(NULL, 'uThukela District', 3, NOW(), NOW()),
(NULL, 'Zululand District', 3, NOW(), NOW()),
(NULL, 'Capricorn District', 4, NOW(), NOW()),
(NULL, 'Mopani District', 4, NOW(), NOW()),
(NULL, 'Sekhukhune District', 4, NOW(), NOW()),
(NULL, 'Vhembe District', 4, NOW(), NOW()),
(NULL, 'Waterberg District', 4, NOW(), NOW()),
(NULL, 'Ehlanzeni District', 5, NOW(), NOW()),
(NULL, 'Gert Sibande District', 5, NOW(), NOW()),
(NULL, 'Nkangala District', 5, NOW(), NOW()),
(NULL, 'Frances Baard District', 6, NOW(), NOW()),
(NULL, 'John Taolo Gaetsewe District', 6, NOW(), NOW()),
(NULL, 'Namakwa District', 6, NOW(), NOW()),
(NULL, 'Pixley Ka Seme District', 6, NOW(), NOW()),
(NULL, 'ZF Mgcawu District', 6, NOW(), NOW()),
(NULL, 'Bojanala Platinum District', 7, NOW(), NOW()),
(NULL, 'Dr Kenneth Kaunda District', 7, NOW(), NOW()),
(NULL, 'Dr Ruth Segomotsi Mompati District', 7, NOW(), NOW()),
(NULL, 'Ngaka Modiri Molema District', 7, NOW(), NOW());
(NULL, 'City of Cape Town Metropolitan', 8, NOW(), NOW()),
(NULL, 'Cape Winelands District', 8, NOW(), NOW()),
(NULL, 'Central Karoo District', 8, NOW(), NOW()),
(NULL, 'Garden Route District', 8, NOW(), NOW()),
(NULL, 'Overberg District', 8, NOW(), NOW()),
(NULL, 'West Coast District', 8, NOW(), NOW()),
(NULL, 'Buffalo City Metropolitan', 9, NOW(), NOW()),
(NULL, 'Nelson Mandela Bay Metropolitan', 9, NOW(), NOW()),
(NULL, 'Alfred Nzo District', 9, NOW(), NOW()),
(NULL, 'Amathole District', 9, NOW(), NOW()),
(NULL, 'Chris Hani District', 9, NOW(), NOW()),
(NULL, 'Joe Gqabi District', 9, NOW(), NOW()),
(NULL, 'OR Tambo District', 9, NOW(), NOW()),
(NULL, 'Sarah Baartman District', 9, NOW(), NOW()),