INSERT INTO `services` (`id`, `service_name`, `industryId`, `created_at`, `updated_at`) VALUES
(NULL, 'Cow Feed', 6, NOW(), NOW()),
(NULL, 'Chicken Feed', 6, NOW(), NOW()),
(NULL, 'Software Sales', 7, NOW(), NOW()),
(NULL, 'Hardware Sales', 7, NOW(), NOW()),
(NULL, 'Amazon Web Services', 7, NOW(), NOW()),
(NULL, 'Oil removal', 8, NOW(), NOW()),
(NULL, 'Kitchen Chemicals', 8, NOW(), NOW()),
(NULL, 'Butchery', 10, NOW(), NOW()),
(NULL, 'Fruit & Vegitables', 10, NOW(), NOW()),
(NULL, 'Squeezed juice', 10, NOW(), NOW()),
(NULL, 'Portfolio management', 1, NOW(), NOW()),
(NULL, 'Capital restructuring', 1, NOW(), NOW()),
(NULL, 'Tax/audit consulting', 1, NOW(), NOW()),
(NULL, 'Treasury/debt instruments', 1, NOW(), NOW()),
(NULL, 'Stock market', 1, NOW(), NOW()),
(NULL, 'Insurance', 1, NOW(), NOW()),
(NULL, 'Mutual funds', 1, NOW(), NOW()),
(NULL, 'Wealth management', 1, NOW(), NOW()),
(NULL, 'Professional advisory', 1, NOW(), NOW()),
(NULL, 'Banking', 1, NOW(), NOW()),
(NULL, 'Some e-commerce businesses', 16, NOW(), NOW()),
(NULL, 'Direct sales catalog and mail order companies', 16, NOW(), NOW()),
(NULL, 'Multichannel stores', 15, NOW(), NOW()),
(NULL, 'Discount stores', 15, NOW(), NOW()),
(NULL, 'Supermarkets and Hypermarkets', 15, NOW(), NOW()),
(NULL, 'Department stores', 15, NOW(), NOW()),
(NULL, 'Drug stores', 15, NOW(), NOW()),
(NULL, 'Home furnishing retailers', 15, NOW(), NOW()),
(NULL, 'Auto retailers', 15, NOW(), NOW()),
(NULL, 'Convenience stores', 15, NOW(), NOW()),
(NULL, 'Grocery stores', 15, NOW(), NOW()),
(NULL, 'Specialty retailers', 15, NOW(), NOW()),
(NULL, 'Clothing stores', 15, NOW(), NOW()),
(NULL, 'Accommodation', 4, NOW(), NOW()),
(NULL, 'Hospitality and related services', 4, NOW(), NOW()),
(NULL, 'Travel and distribution systems', 4, NOW(), NOW()),
(NULL, 'Casinos',3, NOW(), NOW()),
(NULL, 'Cruise',3, NOW(), NOW()),
(NULL, 'Recreation',3, NOW(), NOW()),
(NULL, 'Entertainment',3, NOW(), NOW()),
(NULL, 'Attractions',3, NOW(), NOW()),
(NULL, 'Meetings and events',3, NOW(), NOW()),
(NULL, 'Travel and transportation',3, NOW(), NOW()),
(NULL, 'Food and beverage',3, NOW(), NOW()),
(NULL, 'Textile clothing and footwear', 5, NOW(), NOW()),
(NULL, 'Metals', 5, NOW(), NOW()),
(NULL, 'Electronics', 5, NOW(), NOW()),
(NULL, 'Food processing', 5, NOW(), NOW()),
(NULL, 'Agricultural production', 5, NOW(), NOW()),
(NULL, 'Pulp and paper', 5, NOW(), NOW()),
(NULL, 'Chemical, petrochemical, and pharmaceutical production', 5, NOW(), NOW()),
(NULL, 'Petroleum refining', 5, NOW(), NOW()),
(NULL, 'Oil and gas exploration and production', 5, NOW(), NOW()),
(NULL, 'Mining', 5, NOW(), NOW()),
(NULL, 'Crops', 6, NOW(), NOW()),
(NULL, 'Horticulture', 6, NOW(), NOW()),
(NULL, 'Livestock', 6, NOW(), NOW()),
(NULL, 'Forestry', 6, NOW(), NOW()),
(NULL, 'Telecom equipment', 7, NOW(), NOW()),
(NULL, 'Telecom services', 7, NOW(), NOW()),
(NULL, 'Wireless communication', 7, NOW(), NOW()),
(NULL, 'Orthadontist', 8, NOW(), NOW()),
(NULL, 'Optometrist', 8, NOW(), NOW()),
(NULL, 'General Practitionar', 8, NOW(), NOW()),
(NULL, 'Dentistry', 8, NOW(), NOW());