INSERT INTO `provinces` (`id`, `province`, `created_at`, `updated_at`) VALUES
(NULL, 'Free State', NOW(), NOW()),
(NULL, 'Gauteng', NOW(), NOW()),
(NULL, 'KwaZulu-Natal', NOW(), NOW()),
(NULL, 'Limpopo', NOW(), NOW()),
(NULL, 'Mpumalanga', NOW(), NOW()),
(NULL, 'Northern Cape', NOW(), NOW()),
(NULL, 'North West', NOW(), NOW()),
(NULL, 'Western Cape', NOW(), NOW()),
(NULL, 'Eastern Cape', NOW(), NOW());

INSERT INTO `municipal_districts` (`id`, `municipal_district`, `provinceId`, `created_at`, `updated_at`) VALUES
(NULL, 'Nkangala District', 5, NOW(), NOW()),
(NULL, 'Gert Sibande District', 5, NOW(), NOW()),
(NULL, 'Ehlanzeni District', 5, NOW(), NOW()),
(NULL, 'Mangaung Metropolitan', 1, NOW(), NOW()),
(NULL, 'Xhariep District', 1, NOW(), NOW()),
(NULL, 'Thabo Mofutsanyana District', 1, NOW(), NOW()),
(NULL, 'Lejweleputswa District', 1, NOW(), NOW()),
(NULL, 'Fezile Dabi District', 1, NOW(), NOW()),
(NULL, 'West Rand District', 2, NOW(), NOW()),
(NULL, 'Sedibeng District', 2, NOW(), NOW()),
(NULL, 'City of Ekurhuleni Metropolitan', 2, NOW(), NOW()),
(NULL, 'City of Johannesburg Metropolitan', 2, NOW(), NOW()),
(NULL, 'City of Tshwane Metropolitan', 2, NOW(), NOW()),
(NULL, 'Zululand District', 3, NOW(), NOW()),
(NULL, 'uThukela District', 3, NOW(), NOW()),
(NULL, 'uMzinyathi District', 3, NOW(), NOW()),
(NULL, 'uMkhanyakude District', 3, NOW(), NOW()),
(NULL, 'uMgungundlovu District', 3, NOW(), NOW()),
(NULL, 'Ugu District', 3, NOW(), NOW()),
(NULL, 'King Cetshwayo District', 3, NOW(), NOW()),
(NULL, 'iLembe District', 3, NOW(), NOW()),
(NULL, 'Harry Gwala District', 3, NOW(), NOW()),
(NULL, 'Amajuba District', 3, NOW(), NOW()),
(NULL, 'eThekwini Metropolitan', 3, NOW(), NOW()),
(NULL, 'Capricorn District', 4, NOW(), NOW()),
(NULL, 'Waterberg District', 4, NOW(), NOW()),
(NULL, 'Vhembe District', 4, NOW(), NOW()),
(NULL, 'Sekhukhune District', 4, NOW(), NOW()),
(NULL, 'Mopani District', 4, NOW(), NOW()),
(NULL, 'Buffalo City Metropolitan', 9, NOW(), NOW()),
(NULL, 'Nelson Mandela Bay Metropolitan', 9, NOW(), NOW()),
(NULL, 'Alfred Nzo District', 9, NOW(), NOW()),
(NULL, 'Amathole District', 9, NOW(), NOW()),
(NULL, 'Chris Hani District', 9, NOW(), NOW()),
(NULL, 'Joe Gqabi District', 9, NOW(), NOW()),
(NULL, 'OR Tambo District', 9, NOW(), NOW()),
(NULL, 'Sarah Baartman District', 9, NOW(), NOW()),
(NULL, 'West Coast District', 8, NOW(), NOW()),
(NULL, 'City of Cape Town Metropolitan', 8, NOW(), NOW()),
(NULL, 'Cape Winelands District', 8, NOW(), NOW()),
(NULL, 'Central Karoo District', 8, NOW(), NOW()),
(NULL, 'Garden Route District', 8, NOW(), NOW()),
(NULL, 'Overberg District', 8, NOW(), NOW()),
(NULL, 'ZF Mgcawu District', 6, NOW(), NOW()),
(NULL, 'Pixley Ka Seme District', 6, NOW(), NOW()),
(NULL, 'Namakwa District', 6, NOW(), NOW()),
(NULL, 'John Taolo Gaetsewe District', 6, NOW(), NOW()),
(NULL, 'Frances Baard District', 6, NOW(), NOW()),
(NULL, 'Bojanala Platinum District', 7, NOW(), NOW()),
(NULL, 'Dr Kenneth Kaunda District', 7, NOW(), NOW()),
(NULL, 'Dr Ruth Segomotsi Mompati District', 7, NOW(), NOW()),
(NULL, 'Ngaka Modiri Molema District', 7, NOW(), NOW());

INSERT INTO `municipalities` (`id`, `municipality`, `districtId`, `created_at`, `updated_at`) VALUES
(NULL, 'Bushbuckridge Local', 3, NOW(), NOW()),
(NULL, 'City of Mbombela Local', 3, NOW(), NOW()),
(NULL, 'Nkomazi Local', 3, NOW(), NOW()),
(NULL, 'Thaba Chweu Local', 3, NOW(), NOW()),
(NULL, 'Ngwathe Local', 5, NOW(), NOW()),
(NULL, 'Mafube Local', 5, NOW(), NOW()),
(NULL, 'Metsimaholo Local', 5, NOW(), NOW()),
(NULL, 'Moqhaka Local', 5, NOW(), NOW()),
(NULL, 'City of Ekurhuleni Metropolitan', 12, NOW(), NOW()),
(NULL, 'City of Johannesburg Metropolitan', 13, NOW(), NOW()),
(NULL, 'City of Tshwane Metropolitan', 14, NOW(), NOW()),
(NULL, 'Midvaal Local', 11, NOW(), NOW()),
(NULL, 'Lesedi Local', 11, NOW(), NOW()),
(NULL, 'Emfuleni Local', 11, NOW(), NOW()),
(NULL, 'Merafong City Local', 10, NOW(), NOW()),
(NULL, 'Mogale City Local', 10, NOW(), NOW()),
(NULL, 'Rand West City Local', 10, NOW(), NOW()),
(NULL, 'AbaQulusi Local', 15, NOW(), NOW()),
(NULL, 'eDumbe Local', 15, NOW(), NOW()),
(NULL, 'Nongoma Local', 15, NOW(), NOW()),
(NULL, 'Ulundi Local', 15, NOW(), NOW()),
(NULL, 'uPhongolo Local', 15, NOW(), NOW()),
(NULL, 'Okhahlamba Local', 16, NOW(), NOW()),
(NULL, 'Inkosi Langalibalele Local', 16, NOW(), NOW()),
(NULL, 'Alfred Duma Local', 16, NOW(), NOW()),
(NULL, 'Umvoti Local', 17, NOW(), NOW()),
(NULL, 'Endumeni Local', 17, NOW(), NOW()),
(NULL, 'Nquthu Local', 17, NOW(), NOW()),
(NULL, 'uMsinga Local', 17, NOW(), NOW()),
(NULL, 'Big 5 Hlabisa Local', 18, NOW(), NOW()),
(NULL, 'Jozini Local', 18, NOW(), NOW()),
(NULL, 'Mtubatuba Local', 18, NOW(), NOW()),
(NULL, 'uMhlabuyalingana Local', 18, NOW(), NOW()),
(NULL, 'Impendle Local', 19, NOW(), NOW()),
(NULL, 'uMshwathi Local', 19, NOW(), NOW()),
(NULL, 'uMngeni Local', 19, NOW(), NOW()),
(NULL, 'Richmond Local', 19, NOW(), NOW()),
(NULL, 'Msunduzi Local', 19, NOW(), NOW()),
(NULL, 'Mpofana Local', 19, NOW(), NOW()),
(NULL, 'Mkhambathini Local', 19, NOW(), NOW()),
(NULL, 'Umzumbe Local', 20, NOW(), NOW()),
(NULL, 'Umuziwabantu Local', 20, NOW(), NOW()),
(NULL, 'Umdoni Local', 20, NOW(), NOW()),
(NULL, 'Ray Nkonyeni Local', 20, NOW(), NOW()),
(NULL, 'uMlalazi Local', 21, NOW(), NOW()),
(NULL, 'City of uMhlathuze Local', 21, NOW(), NOW()),
(NULL, 'Mthonjaneni Local', 21, NOW(), NOW()),
(NULL, 'Nkandla Local', 21, NOW(), NOW()),
(NULL, 'uMfolozi Local', 21, NOW(), NOW()),
(NULL, 'KwaDukuza Local', 22, NOW(), NOW()),
(NULL, 'Mandeni Local', 22, NOW(), NOW()),
(NULL, 'Maphumulo Local', 22, NOW(), NOW()),
(NULL, 'Ndwedwe Local', 22, NOW(), NOW()),
(NULL, 'Dr Nkosazana Dlamini Zuma Local', 23, NOW(), NOW()),
(NULL, 'Greater Kokstad Local', 23, NOW(), NOW()),
(NULL, 'Ubuhlebezwe Local', 23, NOW(), NOW()),
(NULL, 'uMzimkhulu Local', 23, NOW(), NOW()),
(NULL, 'Dannhauser Local', 24, NOW(), NOW()),
(NULL, 'eMadlangeni Local', 24, NOW(), NOW()),
(NULL, 'Newcastle Local', 24, NOW(), NOW()),
(NULL, 'eThekwini Metropolitan', 25, NOW(), NOW()),
(NULL, 'Blouberg Local', 26, NOW(), NOW()),
(NULL, 'Lepelle-Nkumpi Local', 26, NOW(), NOW()),
(NULL, 'Molemole Local', 26, NOW(), NOW()),
(NULL, 'Polokwane Local', 26, NOW(), NOW()),
(NULL, 'Maruleng Local', 30, NOW(), NOW()),
(NULL, 'Greater Tzaneen Local', 30, NOW(), NOW()),
(NULL, 'Greater Letaba Local', 30, NOW(), NOW()),
(NULL, 'Greater Giyani Local', 30, NOW(), NOW()),
(NULL, 'Ba-Phalaborwa Local', 30, NOW(), NOW()),
(NULL, 'Makhuduthamaga Local', 29, NOW(), NOW()),
(NULL, 'Fetakgomo Tubatse Local', 29, NOW(), NOW()),
(NULL, 'Ephraim Mogale Local', 29, NOW(), NOW()),
(NULL, 'Elias Motsoaledi Local', 29, NOW(), NOW()),
(NULL, 'Collins Chabane Local', 28, NOW(), NOW()),
(NULL, 'Makhado Local', 28, NOW(), NOW()),
(NULL, 'Musina Local', 28, NOW(), NOW()),
(NULL, 'Thulamela Local', 28, NOW(), NOW()),
(NULL, 'Bela-Bela Local', 27, NOW(), NOW()),
(NULL, 'Lephalale Local', 27, NOW(), NOW()),
(NULL, 'Modimolle-Mookgophong Local', 27, NOW(), NOW()),
(NULL, 'Mogalakwena Local', 27, NOW(), NOW()),
(NULL, 'Thabazimbi Local', 27, NOW(), NOW()),
(NULL, 'Victor Khanye Local', 1, NOW(), NOW()),
(NULL, 'Dr JS Moroka Local', 1, NOW(), NOW()),
(NULL, 'Emakhazeni Local', 1, NOW(), NOW()),
(NULL, 'Emalahleni Local', 1, NOW(), NOW()),
(NULL, 'Steve Tshwete Local', 1, NOW(), NOW()),
(NULL, 'Thembisile Hani Local', 1, NOW(), NOW()),
(NULL, 'Chief Albert Luthuli Local', 2, NOW(), NOW()),
(NULL, 'Msukaligwa Local', 2, NOW(), NOW()),
(NULL, 'Mkhondo Local', 2, NOW(), NOW()),
(NULL, 'Lekwa Local', 2, NOW(), NOW()),
(NULL, 'Govan Mbeki Local', 2, NOW(), NOW()),
(NULL, 'Dr Pixley Ka Isaka Seme Local', 2, NOW(), NOW()),
(NULL, 'Dipaleseng Local', 2, NOW(), NOW()),
(NULL, 'Buffalo City Metropolitan', 31, NOW(), NOW()),
(NULL, 'Nelson Mandela Bay Metropolitan', 32, NOW(), NOW()),
(NULL, 'Matatiele Local', 33, NOW(), NOW()),
(NULL, 'Ntabankulu Local', 33, NOW(), NOW()),
(NULL, 'Umzimvubu Local', 33, NOW(), NOW()),
(NULL, 'Winnie Madikizela-Mandela Local', 33, NOW(), NOW()),
(NULL, 'Raymond Mhlaba Local', 34, NOW(), NOW()),
(NULL, 'Ngqushwa Local', 34, NOW(), NOW()),
(NULL, 'Mnquma Local', 34, NOW(), NOW()),
(NULL, 'Mbhashe Local', 34, NOW(), NOW()),
(NULL, 'Great Kei Local', 34, NOW(), NOW()),
(NULL, 'Amahlathi Local', 34, NOW(), NOW()),
(NULL, 'Emalahleni Local', 35, NOW(), NOW()),
(NULL, 'Engcobo Local', 35, NOW(), NOW()),
(NULL, 'Enoch Mgijima Local', 35, NOW(), NOW()),
(NULL, 'Intsika Yethu Local', 35, NOW(), NOW()),
(NULL, 'Inxuba Yethemba Local', 35, NOW(), NOW()),
(NULL, 'Sakhisizwe Local', 35, NOW(), NOW()),
(NULL, 'Elundini Local', 36, NOW(), NOW()),
(NULL, 'Senqu Local', 36, NOW(), NOW()),
(NULL, 'Walter Sisulu Local', 36, NOW(), NOW()),
(NULL, 'Ingquza Hill Local', 37, NOW(), NOW()),
(NULL, 'King Sabata Dalindyebo Local', 37, NOW(), NOW()),
(NULL, 'Mhlontlo Local', 37, NOW(), NOW()),
(NULL, 'Nyandeni Local', 37, NOW(), NOW()),
(NULL, 'Port St Johns Local', 37, NOW(), NOW()),
(NULL, 'Sundays River Valley Local', 38, NOW(), NOW()),
(NULL, 'Blue Crane Route Local', 38, NOW(), NOW()),
(NULL, 'Dr Beyers Naudé Local', 38, NOW(), NOW()),
(NULL, 'Kouga Local', 38, NOW(), NOW()),
(NULL, 'Koukamma Local', 38, NOW(), NOW()),
(NULL, 'Makana Local', 38, NOW(), NOW()),
(NULL, 'Ndlambe Local', 38, NOW(), NOW()),
(NULL, 'Swartland Local', 39, NOW(), NOW()),
(NULL, 'Saldanha Bay Local', 39, NOW(), NOW()),
(NULL, 'Matzikama Local', 39, NOW(), NOW()),
(NULL, 'Cederberg Local', 39, NOW(), NOW()),
(NULL, 'Bergrivier Local', 39, NOW(), NOW()),
(NULL, 'City of Cape Town Metropolitan', 40, NOW(), NOW()),
(NULL, 'Witzenberg Local', 41, NOW(), NOW()),
(NULL, 'Stellenbosch Local', 41, NOW(), NOW()),
(NULL, 'Langeberg Local', 41, NOW(), NOW()),
(NULL, 'Drakenstein Local', 41, NOW(), NOW()),
(NULL, 'Breede Valley Local', 41, NOW(), NOW()),
(NULL, 'Beaufort West Local', 42, NOW(), NOW()),
(NULL, 'Laingsburg Local', 42, NOW(), NOW()),
(NULL, 'Beaufort West Local', 42, NOW(), NOW()),
(NULL, 'Oudtshoorn Local', 43, NOW(), NOW()),
(NULL, 'Mossel Bay Local', 43, NOW(), NOW()),
(NULL, 'Knysna Local', 43, NOW(), NOW()),
(NULL, 'Kannaland Local', 43, NOW(), NOW()),
(NULL, 'Hessequa Local', 43, NOW(), NOW()),
(NULL, 'George Local', 43, NOW(), NOW()),
(NULL, 'Bitou Local', 43, NOW(), NOW()),
(NULL, 'Theewaterskloof Local', 44, NOW(), NOW()),
(NULL, 'Swellendam Local', 44, NOW(), NOW()),
(NULL, 'Overstrand Local', 44, NOW(), NOW()),
(NULL, 'Cape Agulhas Local', 44, NOW(), NOW()),
(NULL, 'Sol Plaatje Local', 49, NOW(), NOW()),
(NULL, 'Phokwane Local', 49, NOW(), NOW()),
(NULL, 'Magareng Local', 49, NOW(), NOW()),
(NULL, 'Dikgatlong Local', 49, NOW(), NOW()),
(NULL, 'Joe Morolong Local', 48, NOW(), NOW()),
(NULL, 'Gamagara Local', 48, NOW(), NOW()),
(NULL, 'Ga-Segonyana Local', 48, NOW(), NOW()),
(NULL, 'Richtersveld Local', 47, NOW(), NOW()),
(NULL, 'Nama Khoi Local', 47, NOW(), NOW()),
(NULL, 'Khai-Ma Local', 47, NOW(), NOW()),
(NULL, 'Karoo Hoogland Local', 47, NOW(), NOW()),
(NULL, 'Kamiesberg Local', 47, NOW(), NOW()),
(NULL, 'Hantam Local', 47, NOW(), NOW()),
(NULL, 'Umsobomvu Local', 46, NOW(), NOW()),
(NULL, 'Ubuntu Local', 46, NOW(), NOW()),
(NULL, 'Thembelihle Local', 46, NOW(), NOW()),
(NULL, 'Siyathemba Local', 46, NOW(), NOW()),
(NULL, 'Siyancuma Local', 46, NOW(), NOW()),
(NULL, 'Renosterberg Local', 46, NOW(), NOW()),
(NULL, 'Kareeberg Local', 46, NOW(), NOW()),
(NULL, 'Emthanjeni Local', 46, NOW(), NOW()),
(NULL, 'Tsantsabane Local', 45, NOW(), NOW()),
(NULL, 'Kgatelopele Local', 45, NOW(), NOW()),
(NULL, 'Kai !Garib Local', 45, NOW(), NOW()),
(NULL, 'Dawid Kruiper Local', 45, NOW(), NOW()),
(NULL, '!Kheis Local', 45, NOW(), NOW()),
(NULL, 'Kgetlengrivier Local', 50, NOW(), NOW()),
(NULL, 'Madibeng Local', 50, NOW(), NOW()),
(NULL, 'Moretele Local', 50, NOW(), NOW()),
(NULL, 'Moses Kotane Local', 50, NOW(), NOW()),
(NULL, 'Rustenburg Local', 50, NOW(), NOW()),
(NULL, 'City of Matlosana Local', 51, NOW(), NOW()),
(NULL, 'JB Marks Local', 51, NOW(), NOW()),
(NULL, 'Maquassi Hills Local', 51, NOW(), NOW()),
(NULL, 'Greater Taung Local', 52, NOW(), NOW()),
(NULL, 'Kagisano-Molopo Local', 52, NOW(), NOW()),
(NULL, 'Lekwa-Teemane Local', 52, NOW(), NOW()),
(NULL, 'Mamusa Local', 52, NOW(), NOW()),
(NULL, 'Naledi Local', 52, NOW(), NOW()),
(NULL, 'Ditsobotla Local', 53, NOW(), NOW()),
(NULL, 'Mahikeng Local', 53, NOW(), NOW()),
(NULL, 'Ramotshere Moiloa Local', 53, NOW(), NOW()),
(NULL, 'Ratlou Local', 53, NOW(), NOW()),
(NULL, 'Tswaing Local', 53, NOW(), NOW());

INSERT INTO `industries` (`id`, `industry`, `created_at`, `updated_at`) VALUES
(NULL, 'Finance', NOW(), NOW()),
(NULL, 'Wholesale and Retail', NOW(), NOW()),
(NULL, 'Tourism', NOW(), NOW()),
(NULL, 'Hospitality', NOW(), NOW()),
(NULL, 'Manufacturing', NOW(), NOW()),
(NULL, 'Agricultural', NOW(), NOW()),
(NULL, 'Telecommunications', NOW(), NOW()),
(NULL, 'Medical', NOW(), NOW());

INSERT INTO `services` (`id`, `service_name`, `industryId`, `created_at`, `updated_at`) VALUES
(NULL, 'Cow Feed', 9, NOW(), NOW()),
(NULL, 'Chicken Feed', 9, NOW(), NOW()),
(NULL, 'Software Sales', 7, NOW(), NOW()),
(NULL, 'Hardware Sales', 7, NOW(), NOW()),
(NULL, 'Amazon Web Services', 7, NOW(), NOW()),
(NULL, 'Oil removal', 8, NOW(), NOW()),
(NULL, 'Kitchen Chemicals', 8, NOW(), NOW()),
(NULL, 'Butchery', 10, NOW(), NOW()),
(NULL, 'Fruit & Vegitables', 10, NOW(), NOW()),
(NULL, 'Squeezed juice', 10, NOW(), NOW()),
(NULL, 'Portfolio management', 19, NOW(), NOW()),
(NULL, 'Capital restructuring', 19, NOW(), NOW()),
(NULL, 'Tax/audit consulting', 19, NOW(), NOW()),
(NULL, 'Treasury/debt instruments', 19, NOW(), NOW()),
(NULL, 'Stock market', 19, NOW(), NOW()),
(NULL, 'Insurance', 19, NOW(), NOW()),
(NULL, 'Mutual funds', 19, NOW(), NOW()),
(NULL, 'Wealth management', 19, NOW(), NOW()),
(NULL, 'Professional advisory', 19, NOW(), NOW()),
(NULL, 'Banking', 19, NOW(), NOW()),
(NULL, 'Some e-commerce businesses', 20, NOW(), NOW()),
(NULL, 'Direct sales catalog and mail order companies', 20, NOW(), NOW()),
(NULL, 'Multichannel stores', 20, NOW(), NOW()),
(NULL, 'Discount stores', 20, NOW(), NOW()),
(NULL, 'Supermarkets and Hypermarkets', 20, NOW(), NOW()),
(NULL, 'Department stores', 20, NOW(), NOW()),
(NULL, 'Drug stores', 20, NOW(), NOW()),
(NULL, 'Home furnishing retailers', 20, NOW(), NOW()),
(NULL, 'Auto retailers', 20, NOW(), NOW()),
(NULL, 'Convenience stores', 20, NOW(), NOW()),
(NULL, 'Grocery stores', 20, NOW(), NOW()),
(NULL, 'Specialty retailers', 20, NOW(), NOW()),
(NULL, 'Clothing stores', 20, NOW(), NOW()),
(NULL, 'Accommodation', 21, NOW(), NOW()),
(NULL, 'Hospitality and related services', 21, NOW(), NOW()),
(NULL, 'Travel and distribution systems', 21, NOW(), NOW()),
(NULL, 'Casinos', 22, NOW(), NOW()),
(NULL, 'Cruise', 22, NOW(), NOW()),
(NULL, 'Recreation', 22, NOW(), NOW()),
(NULL, 'Entertainment', 22, NOW(), NOW()),
(NULL, 'Attractions', 22, NOW(), NOW()),
(NULL, 'Meetings and events', 22, NOW(), NOW()),
(NULL, 'Tourism', 22, NOW(), NOW()),
(NULL, 'Travel and transportation', 22, NOW(), NOW()),
(NULL, 'Food and beverage', 22, NOW(), NOW()),
(NULL, 'Accommodation', 22, NOW(), NOW()),
(NULL, 'I.T', 23, NOW(), NOW()),
(NULL, 'Textile clothing and footwear', 23, NOW(), NOW()),
(NULL, 'Metals', 23, NOW(), NOW()),
(NULL, 'Electronics', 23, NOW(), NOW()),
(NULL, 'Food processing', 23, NOW(), NOW()),
(NULL, 'Agricultural production', 23, NOW(), NOW()),
(NULL, 'Pulp and paper', 23, NOW(), NOW()),
(NULL, 'Chemical, petrochemical, and pharmaceutical production', 23, NOW(), NOW()),
(NULL, 'Petroleum refining', 23, NOW(), NOW()),
(NULL, 'Oil and gas exploration and production', 23, NOW(), NOW()),
(NULL, 'Mining', 23, NOW(), NOW()),
(NULL, 'Crops', 24, NOW(), NOW()),
(NULL, 'Horticulture', 24, NOW(), NOW()),
(NULL, 'Livestock', 24, NOW(), NOW()),
(NULL, 'Forestry', 24, NOW(), NOW()),
(NULL, 'Telecom equipment', 25, NOW(), NOW()),
(NULL, 'Telecom services', 25, NOW(), NOW()),
(NULL, 'Wireless communication', 25, NOW(), NOW()),
(NULL, 'Orthadontist', 26, NOW(), NOW()),
(NULL, 'Optometrist', 26, NOW(), NOW()),
(NULL, 'General Practitionar', 26, NOW(), NOW()),
(NULL, 'Dentistry', 26, NOW(), NOW());
