INSERT INTO `municipalities` (`id`, `municipality`, `districtId`, `created_at`, `updated_at`) VALUES
(NULL, 'Mangaung Metropolitan', 1, NOW(), NOW()),
(NULL, 'Mafube Local', 2, NOW(), NOW()),
(NULL, 'Metsimaholo Local', 2, NOW(), NOW()),
(NULL, 'Moqhaka Local', 2, NOW(), NOW()),
(NULL, 'Ngwathe Local', 2, NOW(), NOW()),
(NULL, 'Masilonyana Local', 3, NOW(), NOW()),
(NULL, 'Matjhabeng Local', 3, NOW(), NOW()),
(NULL, 'Nala Local', 3, NOW(), NOW()),
(NULL, 'Tokologo Local', 3, NOW(), NOW()),
(NULL, 'Tswelopele Local', 3, NOW(), NOW()),
(NULL, 'Dihlabeng Local', 4, NOW(), NOW()),
(NULL, 'Maluti-A-Phofung Local', 4, NOW(), NOW()),
(NULL, 'Mantsopa Local', 4, NOW(), NOW()),
(NULL, 'Nketoana Local', 4, NOW(), NOW()),
(NULL, 'Phumelela Local', 4, NOW(), NOW()),
(NULL, 'Setsoto Local', 4, NOW(), NOW()),
(NULL, 'Kopanong Local', 5, NOW(), NOW()),
(NULL, 'Letsemeng Local', 5, NOW(), NOW()),
(NULL, 'Mohokare Local', 5, NOW(), NOW()),
(NULL, 'City of Ekurhuleni Metropolitan', 6, NOW(), NOW()),
(NULL, 'City of Johannesburg Metropolitan', 7, NOW(), NOW()),
(NULL, 'City of Tshwane Metropolitan', 8, NOW(), NOW()),
(NULL, 'Emfuleni Local', 9, NOW(), NOW()),
(NULL, 'Lesedi Local', 9, NOW(), NOW()),
(NULL, 'Midvaal Local', 9, NOW(), NOW()),
(NULL, 'Merafong City Local', 10, NOW(), NOW()),
(NULL, 'Mogale City Local', 10, NOW(), NOW()),
(NULL, 'Rand West City Local', 10, NOW(), NOW()),
(NULL, 'eThekwini Metropolitan', 11, NOW(), NOW()),
(NULL, 'Dannhauser Local', 12, NOW(), NOW()),
(NULL, 'eMadlangeni Local', 12, NOW(), NOW()),
(NULL, 'Newcastle Local', 12, NOW(), NOW()),
(NULL, 'Dr Nkosazana Dlamini Zuma Local', 13, NOW(), NOW()),
(NULL, 'Greater Kokstad Local', 13, NOW(), NOW()),
(NULL, 'Ubuhlebezwe Local', 13, NOW(), NOW()),
(NULL, 'uMzimkhulu Local', 13, NOW(), NOW()),
(NULL, 'KwaDukuza Local', 14, NOW(), NOW()),
(NULL, 'Mandeni Local', 14, NOW(), NOW()),
(NULL, 'Maphumulo Local', 14, NOW(), NOW()),
(NULL, 'Ndwedwe Local', 14, NOW(), NOW()),
(NULL, 'City of uMhlathuze Local', 15, NOW(), NOW()),
(NULL, 'Mthonjaneni Local', 15, NOW(), NOW()),
(NULL, 'Nkandla Local', 15, NOW(), NOW()),
(NULL, 'uMfolozi Local', 15, NOW(), NOW()),
(NULL, 'uMlalazi Local', 15, NOW(), NOW()),
(NULL, 'Ray Nkonyeni Local', 16, NOW(), NOW()),
(NULL, 'Umdoni Local', 16, NOW(), NOW()),
(NULL, 'Umuziwabantu Local', 16, NOW(), NOW()),
(NULL, 'Umzumbe Local', 16, NOW(), NOW()),
(NULL, 'Impendle Local', 17, NOW(), NOW()),
(NULL, 'Mkhambathini Local', 17, NOW(), NOW()),
(NULL, 'Mpofana Local', 17, NOW(), NOW()),
(NULL, 'Msunduzi Local', 17, NOW(), NOW()),
(NULL, 'Richmond Local', 17, NOW(), NOW()),
(NULL, 'uMngeni Local', 17, NOW(), NOW()),
(NULL, 'uMshwathi Local', 17, NOW(), NOW()),
(NULL, 'Big 5 Hlabisa Local', 18, NOW(), NOW()),
(NULL, 'Jozini Local', 18, NOW(), NOW()),
(NULL, 'Mtubatuba Local', 18, NOW(), NOW()),
(NULL, 'uMhlabuyalingana Local', 18, NOW(), NOW()),
(NULL, 'Endumeni Local', 19, NOW(), NOW()),
(NULL, 'Nquthu Local', 19, NOW(), NOW()),
(NULL, 'uMsinga Local', 19, NOW(), NOW()),
(NULL, 'Umvoti Local', 19, NOW(), NOW()),
(NULL, 'Alfred Duma Local', 20, NOW(), NOW()),
(NULL, 'Inkosi Langalibalele Local', 20, NOW(), NOW()),
(NULL, 'Okhahlamba Local', 20, NOW(), NOW()),
(NULL, 'AbaQulusi Local', 21, NOW(), NOW()),
(NULL, 'eDumbe Local', 21, NOW(), NOW()),
(NULL, 'Nongoma Local', 21, NOW(), NOW()),
(NULL, 'Ulundi Local', 21, NOW(), NOW()),
(NULL, 'uPhongolo Local', 21, NOW(), NOW()),
(NULL, 'Blouberg Local', 22, NOW(), NOW()),
(NULL, 'Lepelle-Nkumpi Local', 22, NOW(), NOW()),
(NULL, 'Molemole Local', 22, NOW(), NOW()),
(NULL, 'Polokwane Local', 22, NOW(), NOW()),
(NULL, 'Ba-Phalaborwa Local', 23, NOW(), NOW()),
(NULL, 'Greater Giyani Local', 23, NOW(), NOW()),
(NULL, 'Greater Letaba Local', 23, NOW(), NOW()),
(NULL, 'Greater Tzaneen Local', 23, NOW(), NOW()),
(NULL, 'Maruleng Local', 23, NOW(), NOW()),
(NULL, 'Elias Motsoaledi Local', 24, NOW(), NOW()),
(NULL, 'Ephraim Mogale Local', 24, NOW(), NOW()),
(NULL, 'Fetakgomo Tubatse Local', 24, NOW(), NOW()),
(NULL, 'Makhuduthamaga Local', 24, NOW(), NOW()),
(NULL, 'Collins Chabane Local', 25, NOW(), NOW()),
(NULL, 'Makhado Local', 25, NOW(), NOW()),
(NULL, 'Musina Local', 25, NOW(), NOW()),
(NULL, 'Thulamela Local', 25, NOW(), NOW()),
(NULL, 'Bela-Bela Local', 26, NOW(), NOW()),
(NULL, 'Lephalale Local', 26, NOW(), NOW()),
(NULL, 'Modimolle-Mookgophong Local', 26, NOW(), NOW()),
(NULL, 'Mogalakwena Local', 26, NOW(), NOW()),
(NULL, 'Thabazimbi Local', 26, NOW(), NOW()),
(NULL, 'Bushbuckridge Local', 27, NOW(), NOW()),
(NULL, 'City of Mbombela Local', 27, NOW(), NOW()),
(NULL, 'Nkomazi Local', 27, NOW(), NOW()),
(NULL, 'Thaba Chweu Local', 27, NOW(), NOW()),
(NULL, 'Chief Albert Luthuli Local', 28, NOW(), NOW()),
(NULL, 'Dipaleseng Local', 28, NOW(), NOW()),
(NULL, 'Dr Pixley Ka Isaka Seme Local', 28, NOW(), NOW()),
(NULL, 'Govan Mbeki Local', 28, NOW(), NOW()),
(NULL, 'Lekwa Local', 28, NOW(), NOW()),
(NULL, 'Mkhondo Local', 28, NOW(), NOW()),
(NULL, 'Msukaligwa Local', 28, NOW(), NOW()),
(NULL, 'Dr JS Moroka Local', 29, NOW(), NOW()),
(NULL, 'Emakhazeni Local', 29, NOW(), NOW()),
(NULL, 'Emalahleni Local', 29, NOW(), NOW()),
(NULL, 'Steve Tshwete Local', 29, NOW(), NOW()),
(NULL, 'Thembisile Hani Local', 29, NOW(), NOW()),
(NULL, 'Victor Khanye Local', 29, NOW(), NOW()),
(NULL, 'Dikgatlong Local', 30, NOW(), NOW()),
(NULL, 'Magareng Local', 30, NOW(), NOW()),
(NULL, 'Phokwane Local', 30, NOW(), NOW()),
(NULL, 'Sol Plaatje Local', 30, NOW(), NOW()),
(NULL, 'Ga-Segonyana Local', 31, NOW(), NOW()),
(NULL, 'Gamagara Local', 31, NOW(), NOW()),
(NULL, 'Joe Morolong Local', 31, NOW(), NOW()),
(NULL, 'Hantam Local', 32, NOW(), NOW()),
(NULL, 'Kamiesberg Local', 32, NOW(), NOW()),
(NULL, 'Karoo Hoogland Local', 32, NOW(), NOW()),
(NULL, 'Khai-Ma Local', 32, NOW(), NOW()),
(NULL, 'Nama Khoi Local', 32, NOW(), NOW()),
(NULL, 'Richtersveld Local', 32, NOW(), NOW()),
(NULL, 'Emthanjeni Local', 33, NOW(), NOW()),
(NULL, 'Kareeberg Local', 33, NOW(), NOW()),
(NULL, 'Renosterberg Local', 33, NOW(), NOW()),
(NULL, 'Siyancuma Local', 33, NOW(), NOW()),
(NULL, 'Siyathemba Local', 33, NOW(), NOW()),
(NULL, 'Thembelihle Local', 33, NOW(), NOW()),
(NULL, 'Ubuntu Local', 33, NOW(), NOW()),
(NULL, 'Umsobomvu Local', 33, NOW(), NOW()),
(NULL, '!Kheis Local', 34, NOW(), NOW()),
(NULL, 'Dawid Kruiper Local', 34, NOW(), NOW()),
(NULL, 'Kai !Garib Local', 34, NOW(), NOW()),
(NULL, 'Kgatelopele Local', 34, NOW(), NOW()),
(NULL, 'Tsantsabane Local', 34, NOW(), NOW()),
(NULL, 'Kgetlengrivier Local', 35, NOW(), NOW()),
(NULL, 'Madibeng Local', 35, NOW(), NOW()),
(NULL, 'Moretele Local', 35, NOW(), NOW()),
(NULL, 'Moses Kotane Local', 35, NOW(), NOW()),
(NULL, 'Rustenburg Local', 35, NOW(), NOW()),
(NULL, 'City of Matlosana Local', 36, NOW(), NOW()),
(NULL, 'JB Marks Local', 36, NOW(), NOW()),
(NULL, 'Maquassi Hills Local', 36, NOW(), NOW()),
(NULL, 'Greater Taung Local', 37, NOW(), NOW()),
(NULL, 'Kagisano-Molopo Local', 37, NOW(), NOW()),
(NULL, 'Lekwa-Teemane Local', 37, NOW(), NOW()),
(NULL, 'Mamusa Local', 37, NOW(), NOW()),
(NULL, 'Naledi Local', 37, NOW(), NOW()),
(NULL, 'Ditsobotla Local', 38, NOW(), NOW()),
(NULL, 'Mahikeng Local', 38, NOW(), NOW()),
(NULL, 'Ramotshere Moiloa Local', 38, NOW(), NOW()),
(NULL, 'Ratlou Local', 38, NOW(), NOW()),
(NULL, 'Tswaing Local', 38, NOW(), NOW());
(NULL, 'City of Cape Town Metropolitan', 39, NOW(), NOW()),
(NULL, 'Breede Valley Local', 40, NOW(), NOW()),
(NULL, 'Drakenstein Local', 40, NOW(), NOW()),
(NULL, 'Langeberg Local', 40, NOW(), NOW()),
(NULL, 'Stellenbosch Local', 40, NOW(), NOW()),
(NULL, 'Witzenberg Local', 40, NOW(), NOW()),
(NULL, 'Beaufort West Local', 41, NOW(), NOW()),
(NULL, 'Laingsburg Local', 41, NOW(), NOW()),
(NULL, 'Prince Albert Local', 41, NOW(), NOW()),
(NULL, 'Bitou Local', 42, NOW(), NOW()),
(NULL, 'George Local', 42, NOW(), NOW()),
(NULL, 'Hessequa Local', 42, NOW(), NOW()),
(NULL, 'Kannaland Local', 42, NOW(), NOW()),
(NULL, 'Knysna Local', 42, NOW(), NOW()),
(NULL, 'Mossel Bay Local', 42, NOW(), NOW()),
(NULL, 'Oudtshoorn Local', 42, NOW(), NOW()),
(NULL, 'Cape Agulhas Local', 43, NOW(), NOW()),
(NULL, 'Overstrand Local', 43, NOW(), NOW()),
(NULL, 'Swellendam Local', 43, NOW(), NOW()),
(NULL, 'Theewaterskloof Local', 43, NOW(), NOW()),
(NULL, 'Bergrivier Local', 44, NOW(), NOW()),
(NULL, 'Cederberg Local', 44, NOW(), NOW()),
(NULL, 'Matzikama Local', 44, NOW(), NOW()),
(NULL, 'Saldanha Bay Local', 44, NOW(), NOW()),
(NULL, 'Swartland Local', 44, NOW(), NOW()),
(NULL, 'Buffalo City Metropolitan', 45, NOW(), NOW()),
(NULL, 'Nelson Mandela Bay Metropolitan', 46, NOW(), NOW()),
(NULL, 'Matatiele Local', 47, NOW(), NOW()),
(NULL, 'Ntabankulu Local', 47, NOW(), NOW()),
(NULL, 'Umzimvubu Local', 47, NOW(), NOW()),
(NULL, 'Winnie Madikizela-Mandela Local', 47, NOW(), NOW()),
(NULL, 'Amahlathi Local', 48, NOW(), NOW()),
(NULL, 'Great Kei Local', 48, NOW(), NOW()),
(NULL, 'Mbhashe Local', 48, NOW(), NOW()),
(NULL, 'Mnquma Local', 48, NOW(), NOW()),
(NULL, 'Ngqushwa Local', 48, NOW(), NOW()),
(NULL, 'Raymond Mhlaba Local', 48, NOW(), NOW()),
(NULL, 'Dr AB Xuma Local', 49, NOW(), NOW()),
(NULL, 'Emalahleni Local', 49, NOW(), NOW()),
(NULL, 'Enoch Mgijima Local', 49, NOW(), NOW()),
(NULL, 'Intsika Yethu Local', 49, NOW(), NOW()),
(NULL, 'Inxuba Yethemba Local', 49, NOW(), NOW()),
(NULL, 'Sakhisizwe Local', 49, NOW(), NOW()),
(NULL, 'Elundini Local', 50, NOW(), NOW()),
(NULL, 'Senqu Local', 50, NOW(), NOW()),
(NULL, 'Walter Sisulu Local', 50, NOW(), NOW()),
(NULL, 'Ingquza Hill Local', 51, NOW(), NOW()),
(NULL, 'King Sabata Dalindyebo Local', 51, NOW(), NOW()),
(NULL, 'Mhlontlo Local', 51, NOW(), NOW()),
(NULL, 'Nyandeni Local', 51, NOW(), NOW()),
(NULL, 'Port St Johns Local', 51, NOW(), NOW()),
(NULL, 'Blue Crane Route Local', 52, NOW(), NOW()),
(NULL, 'Dr Beyers Naudé Local', 52, NOW(), NOW()),
(NULL, 'Kouga Local', 52, NOW(), NOW()),
(NULL, 'Koukamma Local', 52, NOW(), NOW()),
(NULL, 'Makana Local', 52, NOW(), NOW()),
(NULL, 'Ndlambe Local', 52, NOW(), NOW()),
(NULL, 'Sundays River Valley Local', 52, NOW(), NOW()),